package com.jtech.felizmusic.ui.theme

import android.graphics.Bitmap
import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.SaverScope
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalContext
import androidx.palette.graphics.Palette
import com.jtech.felizmusic.constants.DarkModeKey
import com.jtech.felizmusic.constants.PureBlackKey
import com.jtech.felizmusic.constants.SelectedThemeColorKey
import com.jtech.felizmusic.ui.screens.settings.DarkMode
import com.jtech.felizmusic.utils.rememberEnumPreference
import com.jtech.felizmusic.utils.rememberPreference
import com.materialkolor.PaletteStyle
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.rememberDynamicColorScheme
import com.materialkolor.score.Score

// Legacy sentinel kept for the album-art extraction fallback. It is no longer the app default accent
// (that is [BrandThemeColor]); the "dynamic" palette is driven by DynamicThemeKey, not by this color.
val DefaultThemeColor = Color(0xFFED5564)

/**
 * Whether the UI should render AMOLED pure-black surfaces right now: the preference is on AND
 * dark theme is active (same derivation as MainActivity's theme setup). Use this instead of
 * reading PureBlackKey directly so light mode never goes pure-black.
 */
@Composable
fun rememberPureBlack(): Boolean {
    val pureBlackEnabled by rememberPreference(PureBlackKey, defaultValue = false)
    val darkMode by rememberEnumPreference(DarkModeKey, defaultValue = DarkMode.AUTO)
    val systemDark = isSystemInDarkTheme()
    return remember(pureBlackEnabled, darkMode, systemDark) {
        pureBlackEnabled && (if (darkMode == DarkMode.AUTO) systemDark else darkMode == DarkMode.ON)
    }
}

/**
 * [ZemerTheme] resolved from the user's actual saved preferences — the selected palette
 * ([SelectedThemeColorKey], incl. the System-wallpaper sentinel), dark mode ([DarkModeKey]) and
 * pure-black ([PureBlackKey]). Use this from any Activity/dialog outside MainActivity (the recognition
 * popup, etc.) so they follow the chosen theme instead of the brand default. It intentionally omits the
 * album-art dynamic colour (that needs the player and lives in MainActivity) — a transient popup just
 * uses the selected accent as its fallback.
 */
@Composable
fun ZemerAppTheme(content: @Composable () -> Unit) {
    val darkMode by rememberEnumPreference(DarkModeKey, defaultValue = DarkMode.AUTO)
    val systemDark = isSystemInDarkTheme()
    val useDark = if (darkMode == DarkMode.AUTO) systemDark else darkMode == DarkMode.ON
    val pureBlack = rememberPureBlack()
    val selectedColorInt by rememberPreference(
        SelectedThemeColorKey,
        defaultValue = DefaultAccentColor.toArgb(),
    )
    ZemerTheme(
        darkTheme = useDark,
        pureBlack = pureBlack,
        themeColor = Color(selectedColorInt),
        content = content,
    )
}

@Composable
fun ZemerTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    pureBlack: Boolean = false,
    themeColor: Color = BrandThemeColor,
    content: @Composable () -> Unit,
) {
    val context = LocalContext.current
    // The System palette (its reserved sentinel) uses the platform's Android 12+ wallpaper scheme;
    // every other accent (the brand default, a picked color, or the album-art color when the dynamic
    // palette is active) is generated by materialKolor from that single seed.
    val useSystemWallpaper = themeColor == SystemWallpaperThemeColor &&
        Build.VERSION.SDK_INT >= Build.VERSION_CODES.S
    val baseColorScheme = if (useSystemWallpaper) {
        if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
    } else {
        rememberDynamicColorScheme(
            // Defensive: if the sentinel ever reaches an unsupported device, fall back to the brand seed.
            seedColor = if (themeColor == SystemWallpaperThemeColor) BrandThemeColor else themeColor,
            isDark = darkTheme,
            specVersion = ColorSpec.SpecVersion.SPEC_2025,
            style = PaletteStyle.TonalSpot // Keep existing style
        )
    }

    // Use the FULL materialKolor scheme — surfaces, containers and accents all derive from the one
    // seed, so the whole app (backgrounds, bars, the nav pill, cards) is tonally cohesive: the
    // system-wallpaper "Material You" look. We deliberately do NOT neutralize surfaces; that was what
    // stopped the bars from picking up the theme and left neutral-grey surfaces clashing with a
    // saturated accent. The only override is the brand accent pinning its exact primary family.
    val brandedColorScheme = if (themeColor == BrandThemeColor && darkTheme) {
        baseColorScheme.copy(
            primary = BrandPrimaryDark,
            onPrimary = BrandOnPrimaryDark,
            primaryContainer = BrandPrimaryContainerDark,
            onPrimaryContainer = BrandOnPrimaryContainerDark,
        )
    } else {
        baseColorScheme
    }

    // Dark mode keeps the full materialKolor tinted-grey surfaces (the "dark" look). Pure-black
    // ("BLACK") mode drives every surface to true black via pureBlack(), so the two modes are clearly
    // distinct: dark = tinted grey, black = pure black.
    val colorScheme = remember(brandedColorScheme, pureBlack, darkTheme) {
        if (darkTheme && pureBlack) brandedColorScheme.pureBlack(true) else brandedColorScheme
    }

    // Use standard MaterialTheme instead of MaterialExpressiveTheme
    MaterialTheme(
        colorScheme = colorScheme,
        typography = AppTypography, // Use the defined AppTypography
        content = content
    )
}

fun Bitmap.extractThemeColor(): Color {
    val colorsToPopulation = Palette.from(this)
        .maximumColorCount(8)
        .generate()
        .swatches
        .associate { it.rgb to it.population }
    val rankedColors = Score.score(colorsToPopulation)
    return Color(rankedColors.first())
}

fun Bitmap.extractGradientColors(): List<Color> {
    val extractedColors = Palette.from(this)
        .maximumColorCount(64)
        .generate()
        .swatches
        .associate { it.rgb to it.population }

    val orderedColors = Score.score(extractedColors, 2, 0xff4285f4.toInt(), true)
        .sortedByDescending { Color(it).luminance() }

    return if (orderedColors.size >= 2)
        listOf(Color(orderedColors[0]), Color(orderedColors[1]))
    else
        listOf(Color(0xFF595959), Color(0xFF0D0D0D))
}

fun ColorScheme.pureBlack(apply: Boolean) =
    if (apply) copy(
        // AMOLED "black" mode: the BACKGROUND + bar tones go true black (surface/background and the
        // lower containers, incl. the bar's surfaceContainer). The ELEVATED card tones
        // (surfaceContainerHigh/Highest, surfaceBright) are deliberately kept from the scheme so cards,
        // dialogs and the genre grid stay VISIBLE on the black canvas — blacking them made those cards
        // disappear. Accent slots are left alone.
        surface = Color.Black,
        background = Color.Black,
        surfaceVariant = Color.Black,
        surfaceDim = Color.Black,
        surfaceContainerLowest = Color.Black,
        surfaceContainerLow = Color.Black,
        surfaceContainer = Color.Black,
    ) else this

val ColorSaver = object : Saver<Color, Int> {
    override fun restore(value: Int): Color = Color(value)
    override fun SaverScope.save(value: Color): Int = value.toArgb()
}
